name: Deploy to Cloud Run
on:
  # Disabled automatic deploys on push; run manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_IDP }}
        service_account:          ${{ secrets.GCP_SA_EMAIL }}
    - uses: google-github-actions/setup-gcloud@v2
    - name: Build & push
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/order-scanner \
          --file backend/Dockerfile backend
    - name: Deploy
      run: |
        gcloud run deploy order-scanner                   --image gcr.io/$PROJECT_ID/order-scanner                   --region ${{ secrets.GCP_REGION }}                   --platform managed                   --allow-unauthenticated                   --set-env-vars DATABASE_URL=$DATABASE_URL,SHOPIFY_STORES_JSON=$SHOPIFY_STORES_JSON
